# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3  = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
arr2.ndim, arr2.size, arr2.shape, arr2.dtype, type(arr2)

(2, 6, (2, 3), dtype('int32'), numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
arr3.ndim, arr3.size, arr3.shape, arr3.dtype, type(arr3)

(3, 18, (3, 2, 3), dtype('int32'), numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df2 = pd.DataFrame(arr2)

In [18]:
# Create an array of shape (10, 2) with only ones
uni = np.ones((10,2))
uni

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
niente = np.zeros((7,2,3))
niente

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create an array within a range of 0 and 100 with step 3
arr4 = np.arange(0,100,3)
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr5 = np.random.randint(0,10,size=(7,2))
arr5

array([[9, 4],
       [1, 8],
       [6, 8],
       [3, 5],
       [5, 0],
       [0, 2],
       [1, 5]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr6 = np.random.random(size=(3,5))
arr6

array([[0.34333876, 0.73126102, 0.82690515, 0.4833381 , 0.32412527],
       [0.95890732, 0.38436039, 0.64951022, 0.95587287, 0.2926194 ],
       [0.1742938 , 0.27437647, 0.01957225, 0.15752485, 0.30630854]])

In [39]:
# Set the random seed to 42
np.random.seed(4)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr7 = np.random.random(size=(4,6))
arr7

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882,
        0.2160895 ],
       [0.97627445, 0.00623026, 0.25298236, 0.43479153, 0.77938292,
        0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394, 0.0089861 ,
        0.38657128],
       [0.04416006, 0.95665297, 0.43614665, 0.94897731, 0.78630599,
        0.8662893 ]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [44]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr8 = np.random.randint(1,10,size=(3,7))
arr8
# Find the unique numbers in the array you just created
#np.unique(arr8)

array([[9, 5, 5, 1, 8, 3, 2],
       [9, 9, 2, 4, 2, 4, 7],
       [8, 5, 1, 8, 4, 8, 7]])

In [45]:
# Find the 0'th index of the latest array you created
arr8[0]

array([9, 5, 5, 1, 8, 3, 2])

In [46]:
# Get the first 2 rows of latest array you created
arr8[:2]

array([[9, 5, 5, 1, 8, 3, 2],
       [9, 9, 2, 4, 2, 4, 7]])

In [15]:
# Get the first 2 rows of latest array you created


In [47]:
# Get the first 2 values of the first 2 rows of the latest array
arr8[:2,:2]

array([[9, 5],
       [9, 9]])

In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr9 = np.random.randint(0,10,size=(3,5))
arr10 =np.ones((3,5))

In [54]:
# Add the two arrays together
np.add(arr9,arr10)

array([[ 1.,  6.,  8.,  4.,  9.],
       [ 6., 10.,  2.,  6.,  5.],
       [ 4., 10.,  6.,  7.,  7.]])

In [56]:
# Create another array of ones of shape (5, 3)
arr11 = np.ones((5,3))

In [63]:
# Try add the array of ones and the other most recent array together
np.add(arr9,arr11)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
arr12 = np.ones((3,5))

In [60]:
# Subtract the new array of ones from the other most recent array
arr9-arr12

array([[-1.,  4.,  6.,  2.,  7.],
       [ 4.,  8.,  0.,  4.,  3.],
       [ 2.,  8.,  4.,  5.,  5.]])

In [61]:
# Multiply the ones array with the latest array
arr12*arr9

array([[0., 5., 7., 3., 8.],
       [5., 9., 1., 5., 4.],
       [3., 9., 5., 6., 6.]])

In [64]:
# Take the latest array to the power of 2 using '**'
arr9**2

array([[ 0, 25, 49,  9, 64],
       [25, 81,  1, 25, 16],
       [ 9, 81, 25, 36, 36]], dtype=int32)

In [65]:
# Do the same thing with np.square()
np.square(arr9)

array([[ 0, 25, 49,  9, 64],
       [25, 81,  1, 25, 16],
       [ 9, 81, 25, 36, 36]], dtype=int32)

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(arr9)

5.066666666666666

In [67]:
# Find the maximum of the latest array using np.max()
np.max(arr9)

9

In [68]:
# Find the minimum of the latest array using np.min()
np.min(arr9)

0

In [69]:
# Find the standard deviation of the latest array
np.std(arr9)

2.5420901286583493

In [70]:
# Find the variance of the latest array
np.var(arr9)

6.462222222222222

In [72]:
# Reshape the latest array to (3, 5, 1)
arr9.reshape(3,5,1)

array([[[0],
        [5],
        [7],
        [3],
        [8]],

       [[5],
        [9],
        [1],
        [5],
        [4]],

       [[3],
        [9],
        [5],
        [6],
        [6]]])

In [73]:
# Transpose the latest array
arr9.T

array([[0, 5, 3],
       [5, 9, 9],
       [7, 1, 5],
       [3, 5, 6],
       [8, 4, 6]])

What does the transpose do?

In [80]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr13 = np.random.randint(0,10,size=(3,3))
arr14 = np.random.randint(0,10,size=(3,2))
arr13, arr14

(array([[7, 5, 1],
        [5, 3, 9],
        [3, 0, 9]]),
 array([[7, 6],
        [1, 7],
        [9, 6]]))

In [81]:
# Perform a dot product on the two newest arrays you created
np.dot(arr13,arr14)

array([[ 63,  83],
       [119, 105],
       [102,  72]])

In [84]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr15=np.random.randint(0,10,size=(4,3))
arr16= np.random.randint(0,10,size=(4,3))

In [85]:
# Perform a dot product on the two newest arrays you created
np.dot(arr15,arr16)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [86]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr15,arr16.T)

array([[ 74,  35,  19,  69],
       [136,  82,  66, 137],
       [ 64,  28,  48,  71],
       [ 82,  22,  40,  84]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [88]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr17 = np.random.randint(0,10,size=(4,3))
arr18 = np.random.randint(0,10,size=(4,3))

In [90]:
 arr17,arr18

(array([[9, 1, 0],
        [6, 0, 0],
        [2, 8, 9],
        [0, 2, 9]]),
 array([[1, 5, 3],
        [5, 7, 3],
        [6, 9, 5],
        [8, 3, 6]]))

In [89]:
# Compare the two arrays with '>'
arr17>arr18

array([[ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [91]:
# Compare the two arrays with '>='
arr17>=arr18

array([[ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True]])

In [92]:
# Find which elements of the first array are greater than 7
arr17>7

array([[ True, False, False],
       [False, False, False],
       [False,  True,  True],
       [False, False,  True]])

In [93]:
# Which parts of each array are equal? (try using '==')
arr17==arr18

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [98]:
# Sort one of the arrays you just created in ascending order
np.sort(arr17,axis=0), arr17

(array([[0, 0, 0],
        [2, 1, 0],
        [6, 2, 9],
        [9, 8, 9]]),
 array([[9, 1, 0],
        [6, 0, 0],
        [2, 8, 9],
        [0, 2, 9]]))

In [99]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr17)

array([[2, 1, 0],
       [1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [102]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr17)

0

In [103]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr17)

2

In [104]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr17, axis=1)

array([0, 0, 2, 2], dtype=int64)

In [105]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr17, axis=0)

array([3, 1, 0], dtype=int64)

In [106]:
# Create an array of normally distributed random numbers
np.random.normal(size=(10,10))

array([[-0.17829181, -0.91166247,  0.22481133,  1.00050563, -1.11931743,
        -0.39027183,  0.98994064, -1.71200744,  0.10694162, -0.34495004],
       [-1.35598886,  0.55051514, -1.3202005 , -0.31868241,  0.05826368,
        -0.3323299 ,  1.19649267, -0.19113763, -0.27070891, -1.37149846],
       [-0.51695477,  0.20054057,  1.3693196 , -1.06479427, -0.69719977,
        -1.3066631 , -1.82138449,  1.55589867, -0.2656828 ,  1.20349004],
       [ 0.50877521, -1.13532086,  0.22424532, -2.77436075,  0.50844097,
         0.17457047, -0.25310608,  0.20706827,  0.27401304,  0.63055086],
       [ 1.15216685, -0.90460281,  2.63340508, -1.08024534, -1.1424233 ,
         0.23544239, -0.92059782, -1.97710183,  0.08444609, -0.16693321],
       [-0.27165506, -2.03262146, -0.67414375, -1.53382538, -0.99436246,
         0.18614784, -0.62383863,  1.04835921,  0.34927263, -0.64792707],
       [-0.46978077,  0.01480992,  1.52023325,  0.3612511 ,  0.06559625,
        -0.1952047 , -0.40782776, -1.57437038

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.